# %%
import requests
import pandas as pd
import numpy as np
from pathlib import Path
import h5py
from tqdm import tqdm
import time
import urllib.parse
# %%
uniprot_id = 'P50052' #AGTR2

# Build the search URL with parameters
params = {
    'search': uniprot_id,
    'format': 'json',
    'columns': 'g,gs,up,sc_RNA_Adipocytes,sc_RNA_Alveolar_cells_type_1,sc_RNA_Alveolar_cells_type_2,sc_RNA_Astrocytes,sc_RNA_B-cells,sc_RNA_Basal_keratinocytes,sc_RNA_Basal_prostatic_cells,sc_RNA_Basal_respiratory_cells,sc_RNA_Basal_squamous_epithelial_cells,sc_RNA_Bipolar_cells,sc_RNA_Breast_glandular_cells,sc_RNA_Breast_myoepithelial_cells,sc_RNA_Cardiomyocytes,sc_RNA_Cholangiocytes,sc_RNA_Ciliated_cells,sc_RNA_Club_cells,sc_RNA_Collecting_duct_cells,sc_RNA_Cone_photoreceptor_cells,sc_RNA_Cytotrophoblasts,sc_RNA_dendritic_cells,sc_RNA_Distal_enterocytes,sc_RNA_Distal_tubular_cells,sc_RNA_Ductal_cells,sc_RNA_Early_spermatids,sc_RNA_Endometrial_stromal_cells,sc_RNA_Endothelial_cells,sc_RNA_Enteroendocrine_cells,sc_RNA_Erythroid_cells,sc_RNA_Excitatory_neurons,sc_RNA_Exocrine_glandular_cells,sc_RNA_Extravillous_trophoblasts,sc_RNA_Fibroblasts,sc_RNA_Gastric_mucus-secreting_cells,sc_RNA_Glandular_and_luminal_cells,sc_RNA_granulocytes,sc_RNA_Granulosa_cells,sc_RNA_Hepatocytes,sc_RNA_Hofbauer_cells,sc_RNA_Horizontal_cells,sc_RNA_Inhibitory_neurons,sc_RNA_Intestinal_goblet_cells,sc_RNA_Ionocytes,sc_RNA_Kupffer_cells,sc_RNA_Langerhans_cells,sc_RNA_Late_spermatids,sc_RNA_Leydig_cells,sc_RNA_Lymphatic_endothelial_cells,sc_RNA_Macrophages,sc_RNA_Melanocytes,sc_RNA_Mesothelial_cells,sc_RNA_Microglial_cells,sc_RNA_monocytes,sc_RNA_Mucus_glandular_cells,sc_RNA_Muller_glia_cells,sc_RNA_NK-cells,sc_RNA_Oligodendrocyte_precursor_cells,sc_RNA_Oligodendrocytes,sc_RNA_Oocytes,sc_RNA_Ovarian_stromal_cells,sc_RNA_Pancreatic_endocrine_cells,sc_RNA_Paneth_cells,sc_RNA_Peritubular_cells,sc_RNA_Plasma_cells,sc_RNA_Prostatic_glandular_cells,sc_RNA_Proximal_enterocytes,sc_RNA_Proximal_tubular_cells,sc_RNA_Rod_photoreceptor_cells,sc_RNA_Salivary_duct_cells,sc_RNA_Schwann_cells,sc_RNA_Secretory_cells,sc_RNA_Serous_glandular_cells,sc_RNA_Sertoli_cells,sc_RNA_Skeletal_myocytes,sc_RNA_Smooth_muscle_cells,sc_RNA_Spermatocytes,sc_RNA_Spermatogonia,sc_RNA_Squamous_epithelial_cells,sc_RNA_Suprabasal_keratinocytes,sc_RNA_Syncytiotrophoblasts,sc_RNA_T-cells,sc_RNA_Undifferentiated_cells,t_RNA_adipose_tissue,t_RNA_adrenal_gland,t_RNA_amygdala,t_RNA_appendix,t_RNA_basal_ganglia,t_RNA_bone_marrow,t_RNA_breast,t_RNA_cerebellum,t_RNA_cerebral_cortex,t_RNA_cervix,t_RNA_choroid_plexus,t_RNA_colon,t_RNA_duodenum,t_RNA_endometrium_1,t_RNA_epididymis,t_RNA_esophagus,t_RNA_fallopian_tube,t_RNA_gallbladder,t_RNA_heart_muscle,t_RNA_hippocampal_formation,t_RNA_hypothalamus,t_RNA_kidney,t_RNA_liver,t_RNA_lung,t_RNA_lymph_node,t_RNA_midbrain,t_RNA_ovary,t_RNA_pancreas,t_RNA_parathyroid_gland,t_RNA_pituitary_gland,t_RNA_placenta,t_RNA_prostate,t_RNA_rectum,t_RNA_retina,t_RNA_salivary_gland,t_RNA_seminal_vesicle,t_RNA_skeletal_muscle,t_RNA_skin_1,t_RNA_small_intestine,t_RNA_smooth_muscle,t_RNA_spinal_cord,t_RNA_spleen,t_RNA_stomach_1,t_RNA_testis,t_RNA_thymus,t_RNA_thyroid_gland,t_RNA_tongue,t_RNA_tonsil,t_RNA_urinary_bladder,t_RNA_vagina',
    'compress': 'no'
}
base_url = "https://www.proteinatlas.org"

search_url = f"{base_url}/api/search_download.php?{urllib.parse.urlencode(params)}"
print(f"Searching for UniProt ID: {uniprot_id}")
print(f"URL: {search_url}")
response = requests.get(search_url)
response.raise_for_status()
data = response.json()